package com.corp.cchrs.model;

public enum EHardwareType {
	PC, LAPTOP, PRINTER, NETWORK_PRINTER, MOUSE, KEYBOARD, SCANNER, MONITOR, WEBCAM, 
	SPEAKERS, MICROPHONE, COMPUTER_CHAIR, DESK, UPS, NETWORK_CARD, ROUTER, SWITCH, ACCESS_POINT
}
